### ISSUE TITLE
New webpack version breaks current build

### ISSUE THREAD

**Issue by nlfonseca** [moxystudio/react-with-moxy#93]
If we remove the package-lock.json and run `npm i` the production build breaks.

Error:
```
/Users/nlfonseca/sites/react-with-moxy/node_modules/planify/lib/stdio.js:66
        throw err;
        ^

Error: Path variable [contenthash:15] not implemented in this context: css/main.[contenthash:15].css
    at fn (/Users/nlfonseca/sites/react-with-moxy/node_modules/webpack/lib/TemplatedPathPlugin.js:43:11)
    at fn (/Users/nlfonseca/sites/react-with-moxy/node_modules/webpack/lib/TemplatedPathPlugin.js:31:16)
    at String.replace (<anonymous>)
    at replacePathVariables (/Users/nlfonseca/sites/react-with-moxy/node_modules/webpack/lib/TemplatedPathPlugin.js:98:5)
    at SyncWaterfallHook.eval [as call] (eval at create (/Users/nlfonseca/sites/react-with-moxy/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:7:16)
    at MainTemplate.getAssetPath (/Users/nlfonseca/sites/react-with-moxy/node_modules/webpack/lib/MainTemplate.js:387:31)
    at Compilation.getPath (/Users/nlfonseca/sites/react-with-moxy/node_modules/webpack/lib/Compilation.js:1807:28)
    at getPath (/Users/nlfonseca/sites/react-with-moxy/node_modules/extract-text-webpack-plugin/dist/index.js:315:51)
    at ExtractTextPlugin.extractedChunks.forEach.extractedChunk (/Users/nlfonseca/sites/react-with-moxy/node_modules/extract-text-webpack-plugin/dist/index.js:323:83)
    at Array.forEach (<anonymous>)
    at compilation.hooks.additionalAssets.tapAsync.assetCb (/Users/nlfonseca/sites/react-with-moxy/node_modules/extract-text-webpack-plugin/dist/index.js:301:25)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/nlfonseca/sites/react-with-moxy/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/nlfonseca/sites/react-with-moxy/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeTree.callAsync.err (/Users/nlfonseca/sites/react-with-moxy/node_modules/webpack/lib/Compilation.js:954:32)
    at _err0 (eval at create (/Users/nlfonseca/sites/react-with-moxy/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _async2.default.forEach.err (/Users/nlfonseca/sites/react-with-moxy/node_modules/extract-text-webpack-plugin/dist/index.js:296:11)
```

This seems to be caused by the new web pack 4.5.0 version. According to https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/763#issuecomment-377990665 , a possible fix is to change our `config-client.js`

```
 new ExtractTextPlugin({
    filename: 'css/main.[contenthash:15].css',
    allChunks: true,
    disable: isDev,
}),
```

to 

```
 new ExtractTextPlugin({
    filename: 'css/main.[md5:contenthash:hex:20].css',
    allChunks: true,
    disable: isDev,
}),
```

This might be a good time to investigate `mini-css-extract-plugin`

**Comment by satazor** [comment]
Fixed in master!
